### ISSUE TITLE
composer require not working

### ISSUE THREAD

**Issue by ecompleteClem** [peach-payments/magento2-plugin#1]
Hi Francois,

Please tag versions so that when composer require is used that it pulls the minimum stability of the extension.

Thanks, 

C

$ composer require peachpayments/magento2-plugin

```  Could not find a version of package peachpayments/magento2-plugin matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.  ```

**Comment by rootindex** [comment]
Tagged out version 1.0.0, should resolve @ecompleteClem ?

**Comment by ecompleteClem** [comment]
Looks good! 

Could you up PHP Dependency for ^7.2 as well please?

Thanks so much bru

**Comment by ecompleteClem** [comment]
Still getting this?

  Package peachpayments/magento2-plugin at version  has a PHP requirement incompatible with your PHP version (7.2.27) 

Odd...

**Comment by ecompleteClem** [comment]
I saw in 1.0.1 you did up the dependencies, but for some reason it's not playing nice... 

So I went with 
`composer require peachpayments/magento2-plugin:1.0.1`

Same error.

**Comment by rootindex** [comment]
Packagist is a bit slow through pushes, should be resolved now

**Comment by ecompleteClem** [comment]
I did a --ignore-platform-reqs on my command-line. Did the trick for now.

**Comment by ecompleteClem** [comment]
Thanks again for the promptness, it's much appreciated!

**Comment by ecompleteClem** [comment]
All works now.

**Comment by rootindex** [comment]
Perfect, thanks
