### ISSUE TITLE
Issue with resource.xml

### ISSUE THREAD

**Issue by ecompleteClem** [peach-payments/magento2-plugin#3]
When running cron manually there is an error being experienced.

The XML in file 

vendor/peachpayments/magento2-plugin/etc/resources.xml" is
   invalid:
  Element 'config': Missing child element(s). Expected is ( resource ).
  Line: 5
  Verify the XML and try again.

**Comment by rootindex** [comment]
Which version of the core are you using?

**Comment by ecompleteClem** [comment]
2.3.4

**Comment by rootindex** [comment]
I removed the file as the module does not require any custom acl resources right now.

**Comment by ecompleteClem** [comment]
Thanks.
